sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - demo

jobs:
  include:
    - stage: Dbetl-Backend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dbetl_backend_flowz:$TRAVIS_BRANCH ./service/
      - docker images
      - docker tag dbetl_backend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/dbetl_backend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/dbetl_backend_flowz:$TRAVIS_BRANCH
    - stage: Dbetl-Frontend-Flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t dbetl_frontend_flowz:$TRAVIS_BRANCH --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" ./client/
      - docker images
      - docker tag dbetl_frontend_flowz:$TRAVIS_BRANCH $DOCKER_USERNAME/dbetl_frontend_flowz:$TRAVIS_BRANCH
      - docker push $DOCKER_USERNAME/dbetl_frontend_flowz:$TRAVIS_BRANCH
    - stage: Upgrade Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./upgrade_demo.sh;
         else
            bash ./upgrade.sh;
         fi'
    - stage: Finish Rancher Service
      script:
      - 'if [ ${TRAVIS_BRANCH} = "demo" ]; then
            bash ./finish_demo.sh;
         else
            bash ./finish.sh;
         fi'

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - rbajaniya@officebrain.com
    on_success: always
    on_failure: always
